import { expand, prefixes } from '@zazuko/rdf-vocabularies'

prefixes.dataCube = 'https://rdf-cube-curation.described.at/'

export const TYPE_PROJECT = expand('dataCube:Project')
export const TYPE_SOURCE = expand('dataCube:Source')
export const TYPE_FACT_TABLE = expand('dataCube:FactTable')
export const TYPE_DIMENSION_TABLE = expand('dataCube:DimensionTable')
export const TYPE_TABLE = expand('dataCube:Table')
export const TYPE_COLUMN = expand('dataCube:Column')
export const TYPE_ATTRIBUTE = expand('dataCube:Attribute')
export const TYPE_REFERENCE_ATTRIBUTE = expand('dataCube:ReferenceAttribute')
export const TYPE_VALUE_ATTRIBUTE = expand('dataCube:ValueAttribute')

export const TYPE_OP_VIEW = expand('schema:ViewAction')
export const TYPE_OP_CREATE = expand('schema:CreateAction')
export const TYPE_OP_DELETE = expand('schema:DeleteAction')
export const TYPE_OP_UPDATE = expand('schema:UpdateAction')

export const PROP_NAME = expand('schema:name')
export const PROP_BASE_URI = expand('dataCube:baseUri')
export const PROP_SOURCE = expand('dataCube:source')
export const PROP_PROJECT = expand('dataCube:project')
export const PROP_IDENTIFIER_TEMPLATE = expand('dataCube:identifierTemplate')
export const PROP_IDENTIFIER_COLUMN = expand('dataCube:identifierColumn')
export const PROP_PREDICATE = expand('dataCube:propertyTemplate')
export const PROP_COLUMN = expand('dataCube:column')
export const PROP_DEFAULT = expand('dataCube:default')
export const PROP_DATATYPE = expand('dataCube:datatype')
export const PROP_DATATYPE_PARAMS = expand('dataCube:datatype/parameters')
export const PROP_DATATYPE_PARAM_FORMAT = expand('dataCube:datatype/format')
export const PROP_LANGUAGE = expand('dataCube:language')
export const PROP_TABLE = expand('dataCube:table')
export const PROP_REFERENCED_TABLE = expand('dataCube:referencedTable')
export const PROP_COLUMN_MAPPING = expand('dataCube:columnMapping')
export const PROP_SOURCE_COLUMN = expand('dataCube:sourceColumn')
export const PROP_REFERENCED_COLUMN = expand('dataCube:referencedColumn')
export const PROP_CSV_DELIMITER = expand('dataCube:csvDelimiter')
export const PROP_CSV_QUOTE = expand('dataCube:csvQuote')
export const PROP_GRAPH_URI = expand('dataCube:graphUri')

export const API_PROJECTS = expand('dataCube:api/projects')
export const API_SOURCES = expand('dataCube:api/sources')
export const API_TABLES = expand('dataCube:api/tables')
export const API_SOURCE_COLUMNS = expand('dataCube:api/columns')
export const API_SOURCE_SAMPLE = expand('dataCube:api/sample')
export const API_CELLS = expand('dataCube:api/cells')
export const API_ATTRIBUTES = expand('dataCube:api/attributes')
export const API_PREVIEW = expand('dataCube:api/preview')
export const API_CSVW = expand('dataCube:api/csvwMetadata')
export const API_JOBS = expand('dataCube:api/jobs')
export const API_S3_BUCKET = expand('dataCube:api/s3Bucket')

export const OP_PROJECTS_CREATE = expand('dataCube:api/CreateProject')
export const OP_PROJECT_DELETE = expand('dataCube:api/DeleteProject')
export const OP_PROJECT_EDIT = expand('dataCube:api/ReplaceProject')
export const OP_SOURCES_CREATE = expand('dataCube:api/AddSource')
export const OP_SOURCE_DELETE = expand('dataCube:api/DeleteSource')
export const OP_TABLES_CREATE_DIMENSION = expand('dataCube:api/CreateDimensionTable')
export const OP_TABLES_CREATE_FACT = expand('dataCube:api/PostFactTable')
export const OP_TABLE_EDIT = expand('dataCube:api/EditTable')
export const OP_TABLE_DELETE = expand('dataCube:api/DeleteTable')
export const OP_ATTRIBUTES_CREATE_VALUE = expand('dataCube:api/AddValueAttribute')
export const OP_ATTRIBUTES_CREATE_REFERENCE = expand('dataCube:api/AddReferenceAttribute')
export const OP_ATTRIBUTE_DELETE = expand('dataCube:api/DeleteAttribute')
export const OP_ATTRIBUTE_EDIT = expand('dataCube:api/EditAttribute')
