
version: "3"

services:

  fuseki:
    image: secoresearch/fuseki
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=password
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
