
version: "3"

services:
  analyzer:
    image: "hydrofoil/hydra-analyser"
    network_mode: "host"
    environment:
      ENTRYPOINT_URL: "http://datacube-api.lndo.site/"
  e2e-tests:
    image: hydrofoil/hypertest
    network_mode: "host"
    environment:
      BASE_URI: "http://datacube-api.lndo.site/"
    volumes:
      - ./api/test:/tests
volumes:
  uploads:
