apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-cube-curation
resources:
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: data-cube-curation

bases:
  - server
