BASE <https://rdf-cube-curation.described.at/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
    ?collection
        a hydra:Collection ;
        hydra:member ?source ;
        hydra:totalItems ?count .

    ?source
        schema:name ?name .
}
WHERE {
    BIND (<${this.locals.modelId}/sources> as ?collection)
    BIND (<${this.locals.modelId}> as ?project)

    OPTIONAL {
        ?project <DataCubeModel/source> ?source .
        OPTIONAL { ?source schema:name ?name . }
    }

    {
        SELECT (COUNT(?source) as ?count) WHERE {
            BIND (<${this.locals.modelId}> as ?project)

            ?project <DataCubeModel/source> ?source .
        }
    }
}
