apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534

      containers:
      - name: data-cube-curation
        image: data-cube-curation
        imagePullPolicy: Always

        env:
        - name: SPARQL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: sparql_endpoint
        - name: SPARQL_UPDATE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: sparql_update_endpoint
        - name: READ_MODEL_SPARQL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: read_model_sparql_endpoint
        - name: READ_MODEL_SPARQL_UPDATE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: read_model_sparql_update_endpoint
        - name: SPARQL_ENDPOINT_USERNAME
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: sparql_endpoint_username
        - name: SPARQL_ENDPOINT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: sparql_endpoint_password
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: port
        - name: BASE_URI
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: base_uri
        - name: STORAGE
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: storage
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: aws_secret_access_key
        - name: AWS_S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: aws_s3_endpoint
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: data-cube-curation
              key: aws_s3_bucket

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: http

        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: http

        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 200m
            memory: 300Mi

        securityContext:
          readOnlyRootFilesystem: true