${(() => {
    this.projectId = this.locals.projectId || `${process.env.BASE_URI}project/${projectId}`
    return ''
})()}

BASE <https://rdf-cube-curation.described.at/>
PREFIX schema: <http://schema.org/>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>

CONSTRUCT
{
    ?project a ?projectType ;
      schema:name ?name ;
      <DataCubeProject/sources> ?sources .

    ?sources
        a hydra:Collection ;
        hydra:member ?source ;
        hydra:totalItems ?count .
}
WHERE
{
    BIND (<${this.projectId}> as ?project)
    BIND (<${this.projectId}/sources> as ?sources)

    ?project
        schema:name ?name ;
        a ?projectType .

    OPTIONAL
    {
        ?project <DataCubeProject/source> ?source .
    }

    {
        SELECT (COUNT(?source) as ?count)
        {
            BIND (<${this.projectId}> as ?project)
            BIND (<${this.projectId}/sources> as ?sources)

            OPTIONAL { ?project <DataCubeProject/source> ?source }
        }
    }
}
