${(() => {
    this.projectId = this.locals.projectId || `${process.env.BASE_URI}project/${projectId}`
    return ''
})()}

BASE <https://rdf-cube-curation.described.at/>

CONSTRUCT
{
    <${this.projectId}> ?pp ?po .
}
WHERE
{
    <${this.projectId}> ?pp ?po .
}
