PREFIX api: <https://rdf-cube-curation.described.at/api/>
PREFIX dataCube: <https://rdf-cube-curation.described.at/>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT
{
    ?source api:columns ?columnsCollection .

    ?columnsCollection
        hydra:member ?column ;
        a hydra:Collection ;
        hydra:totalItems ?count .

    ?column ?columnProp ?o .
}
FROM <${this.locals.sourceId}>
WHERE
{
    BIND (<${this.locals.sourceId}> as ?source)
    BIND (<${this.locals.sourceId}/columns> as ?columnsCollection)

    ?source dataCube:column ?column .

    VALUES ?columnProp
    {
        rdf:type
        schema:name
    }

    ?column ?columnProp ?o .

    {
        SELECT (COUNT(?column) as ?count)
        {
            BIND (<${this.locals.sourceId}> as ?source)

            ?source dataCube:column ?column .
        }
    }
}
