BASE <https://rdf-cube-curation.described.at/>

PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT
{
    ?source ?prop ?value .

    ?source <DataCubeSource/csvwMetadata> <${this.locals.sourceId}/csvw> .
}
WHERE
{
    BIND (<${this.locals.sourceId}> as ?source)

    VALUES ?prop
    {
        rdf:type
        schema:name
    }

    OPTIONAL {
        ?source ?prop ?value .
    }
}
