PREFIX api: <https://rdf-cube-curation.described.at/api/>
PREFIX dataCube: <https://rdf-cube-curation.described.at/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
BASE <${this.env.BASE_URI}>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
    <projects>
        a hydra:Collection ;
        hydra:member ?project ;
        hydra:totalItems ?count .

    ?project
        schema:name ?name ;
        dataCube:baseUri ?baseUri ;
        a ?projectType .
}
WHERE {
    OPTIONAL { ?project a dataCube:Project . }

    OPTIONAL { ?project schema:name ?name . }
    OPTIONAL { ?project dataCube:baseUri ?baseUri . }
    OPTIONAL { ?project a ?projectType . }

    {
        SELECT (COUNT(?p) as ?count) WHERE {
            ?p a dataCube:Project .
        }
    }
}
