name: Build CLI docker image

on:
  push:
    branches-ignore: master
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          dockerfile: cli.Dockerfile
          push: false
